
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HRZhao
 */
public class SendFrame extends javax.swing.JFrame {

    /**
     * Creates new form SendFrame
     */
    public SendFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_send = new javax.swing.JButton();
        txt_url = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_result = new javax.swing.JTextArea();
        txt_fromUserName = new javax.swing.JTextField();
        txt_toUserName = new javax.swing.JTextField();
        btn_copy = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_stop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_content = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_msgId = new javax.swing.JTextField();
        txt_msgType = new javax.swing.JTextField();
        txt_x = new javax.swing.JTextField();
        txt_y = new javax.swing.JTextField();
        txt_pic = new javax.swing.JTextField();
        txt_scale = new javax.swing.JTextField();
        txt_label = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_send.setText("发送");
        btn_send.setName("btn_send"); // NOI18N
        btn_send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sendMouseClicked(evt);
            }
        });

        txt_url.setText("http://localhost:8080/Demo/Enterance");
        txt_url.setName("txt_url"); // NOI18N

        txt_result.setColumns(20);
        txt_result.setRows(5);
        jScrollPane1.setViewportView(txt_result);

        txt_fromUserName.setText("aa");

        txt_toUserName.setText("gh_5a402ba88fa0");

        btn_copy.setText("Copy");
        btn_copy.setName("btn_copy"); // NOI18N
        btn_copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_copyMouseClicked(evt);
            }
        });

        btn_clear.setText("清除");
        btn_clear.setName("btn_clear"); // NOI18N
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearMouseClicked(evt);
            }
        });

        btn_stop.setText("Stop");
        btn_stop.setName("btn_stop"); // NOI18N
        btn_stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_stopMouseClicked(evt);
            }
        });

        jLabel1.setText("URL");

        jLabel2.setText("fromUserName");

        jLabel3.setText("toUserName");

        jLabel4.setText("content");

        jLabel5.setText("msgId");

        txt_msgType.setText("text");

        txt_x.setText("113.1986618");
        txt_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_xActionPerformed(evt);
            }
        });

        txt_y.setText("22.6415015");

        txt_pic.setText("http://mmbiz.qpic.cn/mmbiz/8DgJya2a4eiciagUNbStichEmr2ouIDqe8RLtxN6yc6Fvab2RQyG5L7UlBxEzGNbIticu0nW3rG0p8KbibFiaTSRYy2A/0");

        txt_scale.setText("13");

        txt_label.setText("广东省");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_url, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(btn_copy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_send, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_y, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_x, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_msgType, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_toUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(txt_fromUserName, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(232, 232, 232)
                                        .addComponent(btn_stop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(6, 6, 6)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_content, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_msgId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(txt_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txt_scale, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_label)))))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_send)
                    .addComponent(txt_url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fromUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_copy)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txt_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_toUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_clear)
                            .addComponent(jLabel5)
                            .addComponent(txt_msgId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_stop)
                            .addComponent(txt_msgType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_scale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txt_url.getAccessibleContext().setAccessibleName("");
        jLabel1.getAccessibleContext().setAccessibleName("lbl_url");
        jLabel2.getAccessibleContext().setAccessibleName("lbl_fromUserName");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sendMouseClicked
        // TODO add your handling code here:
        Long s = new Date().getTime();
        String srcXml = getXml();
        send(srcXml);
        Long e = new Date().getTime();
        String txtStr = txt_result.getText();
        txtStr += "{" + (e - s)+"}";
        txt_result.setText(txtStr);
    }//GEN-LAST:event_btn_sendMouseClicked

    private int count = 0;
    private void send(String srcXml){
        count++;
         try {
            String urlStr = txt_url.getText();
            URL url = new URL(urlStr);
            URLConnection con = url.openConnection();
            con.setDoOutput(true);
            con.setRequestProperty("Pragma:", "no-cache");
            con.setRequestProperty("Cache-Control", "no-cache");
            con.setRequestProperty("Content-Type", "text/xml");
             try (OutputStreamWriter out = new OutputStreamWriter(con.getOutputStream())) {
                 String outText= txt_result.getText();
                 outText += "\n|-------------------------------"+count+"------------------------------------|\n";
                 outText += urlStr + "\n";
                 outText += srcXml + "\n";
                 txt_result.setText(outText);
                 out.write(new String(srcXml.getBytes("UTF-8")));
                 out.flush();
             }
            BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream(),"UTF-8"));
            String line = "";
            for (line = br.readLine(); line != null; line = br.readLine()) {
                 String outText= txt_result.getText();
                outText += line + "\n";
                txt_result.setText(outText);
            }
        } catch (MalformedURLException e) {
            String outText= txt_result.getText();
            outText += e.toString() + "\n";
            txt_result.setText(outText);
        } catch (IOException e) {
            String outText= txt_result.getText();
            outText += e.toString() + "\n";
            txt_result.setText(outText);
        }
    }
    private String getXml(){
        StringBuilder sb = new StringBuilder();
        String content = txt_content.getText();
        String fromUserName = txt_fromUserName.getText();
        String toUserName = txt_toUserName.getText();
        String msgId = txt_msgId.getText();
        String  msgType = txt_msgType.getText();
        String picUrl = txt_pic.getText();
        String location_x = txt_x.getText();
        String location_y = txt_y.getText();
        String location_scale = txt_scale.getText();
        String location_label = txt_label.getText();
        Date date = new Date();
        Long createTime = date.getTime()/100;
        if(msgId == null || msgId.equals("")){
            msgId = date.getTime()+"";
        }
        sb.append("<xml>\n");
        sb.append(("\t<ToUserName><![CDATA["+toUserName+"]]></ToUserName>\n"));
        sb.append(("\t<FromUserName><![CDATA["+fromUserName+"]]></FromUserName>\n"));
        sb.append(("\t<CreateTime>" + createTime + "</CreateTime>\n"));
        sb.append(("\t<MsgType><![CDATA["+msgType+"]]></MsgType>\n"));
        sb.append(("\t<MsgId>"+msgId+"</MsgId>\n"));
        switch (msgType) {
            case "image":
                sb.append(("\t<PicUrl><![CDATA[" + picUrl + "]]></PicUrl>\n"));
                break;
            case "location":
                sb.append(("\t<Location_X>" + location_x + "</Location_X>\n"));
                sb.append(("\t<Location_Y>" + location_y + "</Location_Y>\n"));
                sb.append(("\t<Scale>" + location_scale + "</Scale>\n"));
                sb.append(("\t<Label><![CDATA[" + location_label + "]]></Label>\n"));
                break;
            default:
                sb.append(("\t<Content><![CDATA[" + content + "]]></Content>\n"));
                break;
        }
        sb.append(("</xml>"));
        return sb.toString();
    }
    private void btn_copyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_copyMouseClicked
        // TODO add your handling code here:
        txt_result.copy();
      
    }//GEN-LAST:event_btn_copyMouseClicked

    private void btn_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseClicked
        // TODO add your handling code here:
        txt_result.setText("");
        count = 0;
    }//GEN-LAST:event_btn_clearMouseClicked

    private void btn_stopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stopMouseClicked
        // TODO add your handling code here:
        txt_result.selectAll();
    }//GEN-LAST:event_btn_stopMouseClicked

    private void txt_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_xActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_copy;
    private javax.swing.JButton btn_send;
    private javax.swing.JButton btn_stop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_content;
    private javax.swing.JTextField txt_fromUserName;
    private javax.swing.JTextField txt_label;
    private javax.swing.JTextField txt_msgId;
    private javax.swing.JTextField txt_msgType;
    private javax.swing.JTextField txt_pic;
    private javax.swing.JTextArea txt_result;
    private javax.swing.JTextField txt_scale;
    private javax.swing.JTextField txt_toUserName;
    private javax.swing.JTextField txt_url;
    private javax.swing.JTextField txt_x;
    private javax.swing.JTextField txt_y;
    // End of variables declaration//GEN-END:variables
}
